name: Daily Hitokoto to Flomo

#on:
#  schedule:
#    - cron: '0 0 * * *' # 每天 UTC 0:00 运行，对应北京时间 8:00

on:
  push:
    branches:
      - main  # 或者你的主分支名称

jobs:
  send-hitokoto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        run: |
          python << EOF
          import requests

          # 获取一言
          hitokoto_url = "https://v1.hitokoto.cn/"
          hitokoto_response = requests.get(hitokoto_url)
          hitokoto_response.raise_for_status()
          hitokoto = hitokoto_response.json()['hitokoto']
          hitokoto_from = hitokoto_response.json()['from']
          hitokoto_fromwho = hitokoto_response.json()['from_who']

          # flomo API 地址
          flomo_url = "https://flomoapp.com/iwh/MTQzNzU5NA/47c8d9b61c1e5cc8fcb602ca137d5452/"

          # 发送 POST 请求到 flomo
          headers = {
              "Content-Type": "application/json"
          }
          data = {
              "content": f"#一言\n{hitokoto}\n——{hitokoto_fromwho}（{hitokoto_from}）"
          }

          try:
              flomo_response = requests.post(flomo_url, headers=headers, json=data)
              flomo_response.raise_for_status()
              print("一言已成功发送到 flomo!")

          except requests.exceptions.RequestException as e:
              print("发送一言到 flomo 时出错:", e)
          EOF
