name: Daily Hitokoto

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 执行

jobs:
  send-hitokoto:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Hitokoto
        id: fetch-hitokoto
        uses: actions/github-script@v6
        with:
          script: |
            const response = await fetch('https://v1.hitokoto.cn');
            const data = await response.json();
            return data.hitokoto;

      - name: Send to Server酱
        uses: actions/github-script@v6
        with:
          script: |
            const hitokoto = `"${{ steps.fetch-hitokoto.outputs.result }}"`;
            const serverChanKey = ${{ secrets.SERVERCHAN_KEY }}; // 从 secrets 中读取 Server酱 的 key
            const res = await fetch(`https://sctapi.ftqq.com/${serverChanKey}.send?title=一言&desp=` + encodeURIComponent(hitokoto));
            console.log(await res.text());
        env:
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }} 

